package com.smartcampus.model;
public enum NotificationType {
    BOOKING_CREATED, BOOKING_APPROVED, BOOKING_REJECTED, BOOKING_CANCELLED,
    TICKET_CREATED, TICKET_UPDATED, TICKET_ASSIGNED, TICKET_RESOLVED, COMMENT_ADDED,
    SYSTEM_ALERT, CRITICAL_ANNOUNCEMENT
}
