# Server
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://db_user:user%40123@it3030-paf-2026-smart-c.oi5o5p8.mongodb.net/?appName=it3030-paf-2026-smart-campus-group08
spring.data.mongodb.database=smart_campus

# JWT
app.jwt.secret=SmartCampusHub2026VeryLongSecretKeyForJWTTokenGenerationThatIsAtLeast512Bits
app.jwt.expiration=86400000

# Google OAuth2
app.google.client-id=920464662688-t428j48754052jol1l7ta2bj21sims3o.apps.googleusercontent.com

# CORS
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Multipart
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=45MB

# Logging
logging.level.com.smartcampus=DEBUG

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
